[package]
name = "sdl2-demo"
version = "0.1.0"
authors = ["walter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
